version: '3.8'

services:
  kiwi-api:
    image: ghcr.io/ethanzhrepo/kiwi-api:latest
    container_name: kiwi-api
    restart: unless-stopped
    volumes:
      - ../.config:/app/config:ro
      - ../.data:/app/data
    ports:
      - "${API_PORT:-8080}:${API_PORT:-8080}"
    env_file:
      - ../.env
    environment:
      - CHAIN_CONFIG_FILE=/app/config/evm_chains.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${API_PORT:-8080}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 16G
        reservations:
          cpus: '2'
          memory: 1G
    networks:
      - kiwi-network

networks:
  kiwi-network:
    driver: bridge
